Repository zilliztech/akcio, pull requests merged in 2023-10, with the labels that each got.

#84 update ernie llm with eb_bot_sdk
  .github/workflows/unit_test.yml
  config.py
  src_langchain/llm/ernie.py
  test_requirements.txt
  tests/unit_tests/src_langchain/llm/test_ernie.py
Labels: approved, lgtm, size/L

#86 Fix http of default milvus uri
  config.py
  tests/requirements.txt
  tests/unit_tests/src_langchain/llm/test_ernie.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
Labels: approved, lgtm, size/S

#87 Fix bug in gradio
  gradio_demo.py
Labels: approved, lgtm, size/XS

#88 Replace postgresql with sql in langchain
  README.md
  config.py
  src_langchain/store/README.md
  src_langchain/store/__init__.py
  src_langchain/store/memory_store/sql.py
  src_langchain/store/vector_store/milvus.py
  src_towhee/pipelines/__init__.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
Labels: approved, lgtm, size/L

#89 Update README
  README.md
Labels: approved, lgtm, size/XS

#90 support langchain new version and set agent False as default
  main.py
  requirements.txt
  src_langchain/agent/chat_agent.py
  src_langchain/data_loader/data_parser.py
  src_langchain/operations.py
Labels: approved, lgtm, size/M

#91 update ernie setup in readme
  README.md
Labels: approved, lgtm, size/XS

#92 fix ernie operator setup
  src_towhee/pipelines/utils.py
Labels: approved, lgtm, size/XS
