Repository zilliztech/akcio, pull requests merged in 2023-08, with the labels that each got.

#50 Update README.md to correct typo.
  README.md
Labels: approved, lgtm, size/XS

#51 Allow file upload in fastapi
  OWNERS
  main.py
Labels: approved, lgtm, size/S

#52 Update osschat architecture pic
  pics/osschat.png
Labels: approved, lgtm, size/XS

#53 Update README
  README.md
  pics/gradio_query.gif
  pics/osschat_web.png
Labels: approved

#54 Update pics in README
  README.md
Labels: approved, lgtm

#60 Add rewrite_query in towhee mode
  Dockerfile
  config.py
  gradio_demo.py
  main.py
  src_langchain/operations.py
  src_towhee/operations.py
  src_towhee/pipelines/__init__.py
  src_towhee/pipelines/insert/__init__.py
  src_towhee/pipelines/insert/generate_questions.py
  src_towhee/pipelines/search/__init__.py
  src_towhee/pipelines/search/prompts.py
  src_towhee/pipelines/search/rewrite_query.py
  src_towhee/pipelines/utils.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
  tests/unit_tests/src_towhee/pipelines/test_prompts.py
  tests/unit_tests/src_towhee/test_operations.py
Labels: approved, lgtm, size/L

#61 Add generate_questions in insert pipeline
  config.py
  requirements.txt
  src_towhee/operations.py
  src_towhee/pipelines/__init__.py
  src_towhee/pipelines/insert/generate_questions.py
  src_towhee/pipelines/search/prompts.py
  src_towhee/pipelines/utils.py
Labels: approved, lgtm, size/M

#62 Update elastic connection
  config.py
  requirements.txt
  src_towhee/pipelines/__init__.py
  src_towhee/pipelines/insert/generate_questions.py
Labels: approved, lgtm, size/M

#63 Fix FileUpload in fastapi
  README.md
  config.py
  main.py
Labels: approved, lgtm, size/M

#66 chinese prompt
  config.py
  src_towhee/pipelines/search/__init__.py
  src_towhee/pipelines/search/prompts.py
  src_towhee/pipelines/search/rewrite_query.py
  src_towhee/prompts/__init__.py
  src_towhee/prompts/en.py
  src_towhee/prompts/zh.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
  tests/unit_tests/src_towhee/pipelines/test_prompts.py
Labels: approved, lgtm, size/L

#68 fix pylint
  .github/workflows/pylint.yml
  src_towhee/pipelines/search/__init__.py
Labels: approved, lgtm, size/S

#67 Support multiple language modes
  .github/workflows/pylint.yml
  config.py
  src_towhee/pipelines/search/__init__.py
  src_towhee/pipelines/search/prompts.py
  src_towhee/pipelines/search/rewrite_query.py
  src_towhee/prompts/__init__.py
  src_towhee/prompts/en.py
  src_towhee/prompts/zh.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
  tests/unit_tests/src_towhee/pipelines/test_prompts.py
Labels: approved, lgtm, size/L

#69 refactor rewriting query
  src_towhee/pipelines/search/rewrite_query.py
Labels: approved, lgtm, size/M

#72 Support more APIs in main.py
  gradio_demo.py
  main.py
Labels: approved, lgtm, size/M

#73 Add data count
  .gitignore
  OWNERS
  config.py
  main.py
  src_langchain/operations.py
  src_langchain/store/__init__.py
  src_langchain/store/scalar_store/es.py
  src_langchain/store/vector_store/milvus.py
  src_towhee/operations.py
  src_towhee/pipelines/__init__.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
  tests/unit_tests/src_towhee/test_operations.py
Labels: approved, lgtm, size/L

#74 Support env variables for both cloud id & hosts in elastic connection
  config.py
Labels: approved, lgtm, size/S

#75 Improve error handle
  src_towhee/pipelines/insert/__init__.py
  src_towhee/pipelines/search/__init__.py
Labels: approved, lgtm, size/XS

#64 Import prometheus client to collect metrics
  .coverage
  main.py
  moniter.py
  requirements.txt
Labels: approved, lgtm, size/L
