Repository zilliztech/akcio, pull requests merged in 2023-07, with the labels that each got.

#38 Refactor
  .github/workflows/pylint.yml
  README.md
  gradio_demo.py
  main.py
  offline_tools/insert.py
  offline_tools/utils/load_npy.py
  src_langchain/__init__.py
  src_langchain/agent/README.md
  src_langchain/agent/__init__.py
  src_langchain/agent/chat_agent.py
  src_langchain/agent/output_parser.py
  src_langchain/agent/prompt.py
  src_langchain/data_loader/README.md
  src_langchain/data_loader/__init__.py
  src_langchain/data_loader/data_parser.py
  src_langchain/data_loader/data_splitter.py
  src_langchain/embedding/README.md
  src_langchain/embedding/__init__.py
  src_langchain/embedding/langchain_huggingface.py
  src_langchain/embedding/openai_embedding.py
  src_langchain/llm/README.md
  src_langchain/llm/__init__.py
  src_langchain/llm/dolly_chat.py
  src_langchain/llm/ernie.py
  src_langchain/llm/minimax_chat.py
  src_langchain/llm/openai_chat.py
  src_langchain/operations.py
  src_langchain/store/README.md
  src_langchain/store/__init__.py
  src_langchain/store/memory_store/__init__.py
  src_langchain/store/memory_store/pg.py
  src_langchain/store/scalar_store/__init__.py
  src_langchain/store/scalar_store/es.py
  src_langchain/store/vector_store/__init__.py
  src_langchain/store/vector_store/milvus.py
  src_towhee/base.py
  src_towhee/memory/README.md
  src_towhee/memory/__init__.py
  src_towhee/memory/sql.py
  src_towhee/operations.py
  src_towhee/pipelines/README.md
  src_towhee/pipelines/__init__.py
  src_towhee/pipelines/prompts.py
  tests/unit_tests/langchain_src/agent/test_agent.py
  tests/unit_tests/langchain_src/agent/test_output_parser.py
  tests/unit_tests/langchain_src/data_loader/test_data_parser.py
  tests/unit_tests/langchain_src/data_loader/test_data_splitter.py
  tests/unit_tests/langchain_src/llm/test_dolly_chat.py
  tests/unit_tests/langchain_src/llm/test_ernie.py
  tests/unit_tests/langchain_src/llm/test_openai_chat.py
  tests/unit_tests/towhee_src/memory/test_sql.py
  tests/unit_tests/towhee_src/pipelines/test_pipelines.py
  tests/unit_tests/towhee_src/pipelines/test_prompts.py
  tests/unit_tests/towhee_src/test_operations.py
Labels: approved, size/M

#39 Update gradio pics
  gradio_demo.py
  main.py
  pics/gradio_insert.png
  pics/gradio_query.gif
  pics/gradio_query.png
  pics/gradio_ui.png
  src_towhee/memory/sql.py
Labels: approved

#40 Update LICENSE
  LICENSE
  README.md
  ToS.md
  pics/gradio_query.gif
Labels: approved, lgtm

#41 Add ci
  .github/mergify.yml
  .github/stale.yml
  .github/workflows/unit_test.yml
  Contributing.md
  config.py
  gradio_demo.py
  main.py
  offline_tools/generator_questions/__init__.py
  offline_tools/generator_questions/question_generator.py
  offline_tools/insert.py
  offline_tools/utils/load_npy.py
  offline_tools/utils/stackoverflow_json2csv.py
  src_langchain/agent/output_parser.py
  src_langchain/data_loader/data_parser.py
  src_langchain/embedding/langchain_huggingface.py
  src_langchain/embedding/openai_embedding.py
  src_langchain/llm/__init__.py
  src_langchain/llm/dolly_chat.py
  src_langchain/llm/ernie.py
  src_langchain/llm/minimax_chat.py
  src_langchain/llm/openai_chat.py
  src_langchain/operations.py
  src_langchain/store/__init__.py
  src_langchain/store/memory_store/pg.py
  src_langchain/store/scalar_store/es.py
  src_langchain/store/vector_store/milvus.py
  src_towhee/base.py
  src_towhee/memory/sql.py
  src_towhee/operations.py
  src_towhee/pipelines/__init__.py
  tests/requirements.txt
  tests/unit_tests/src_langchain/__init__.py
  tests/unit_tests/src_langchain/agent/__init__.py
  tests/unit_tests/src_langchain/agent/test_agent.py
  tests/unit_tests/src_langchain/agent/test_output_parser.py
  tests/unit_tests/src_langchain/data_loader/__init__.py
  tests/unit_tests/src_langchain/data_loader/test_data_parser.py
  tests/unit_tests/src_langchain/data_loader/test_data_splitter.py
  tests/unit_tests/src_langchain/llm/__init__.py
  tests/unit_tests/src_langchain/llm/test_dolly_chat.py
  tests/unit_tests/src_langchain/llm/test_ernie.py
  tests/unit_tests/src_langchain/llm/test_openai_chat.py
  tests/unit_tests/src_towhee/__init__.py
  tests/unit_tests/src_towhee/memory/__init__.py
  tests/unit_tests/src_towhee/memory/test_sql.py
  tests/unit_tests/src_towhee/pipelines/__init__.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
  tests/unit_tests/src_towhee/pipelines/test_prompts.py
  tests/unit_tests/src_towhee/test_operations.py
  tests/unit_tests/towhee_src/pipelines/test_pipelines.py
Labels: approved, size/XXL

#42 Update codes to pass ci
  .github/workflows/unit_test.yml
  config.py
  src_towhee/pipelines/__init__.py
  tests/requirements.txt
  tests/unit_tests/src_langchain/data_loader/test_data_parser.py
  tests/unit_tests/src_towhee/pipelines/test_pipelines.py
Labels: approved, size/L

#45 Fix zilliz cloud connection issue
  src_langchain/operations.py
  src_towhee/operations.py
  src_towhee/pipelines/__init__.py
Labels: approved, size/S

#46 Support dynamic schema of Milvus in Towhee mode
  src_towhee/pipelines/__init__.py
Labels: approved, lgtm, size/XS

#47 add embedding test
  src_langchain/embedding/openai_embedding.py
  tests/requirements.txt
  tests/unit_tests/src_langchain/embedding/__init__.py
  tests/unit_tests/src_langchain/embedding/test_langchain_huggingface.py
  tests/unit_tests/src_langchain/embedding/test_openai_embedding.py
Labels: approved, lgtm, size/M

#48 Change some classmethod to staticmethod
  src_langchain/store/__init__.py
  src_langchain/store/memory_store/pg.py
  src_langchain/store/scalar_store/es.py
  src_langchain/store/vector_store/milvus.py
Labels: approved, lgtm, size/M

#49 Add Llama-2
  README.md
  config.py
  src_towhee/memory/sql.py
Labels: approved, lgtm, size/M
